steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/PROJECT_NAME/CONTAINER_NAME:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/PROJECT_NAME/CONTAINER_NAME']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'popin-backend',
        '--region=asia-east1',
        '--platform=managed',
        '--image=gcr.io/PROJECT_NAME/CONTAINER_NAME:$SHORT_SHA',
      ]
